# theme = "gruvbox"
# theme = "catppuccin_mocha"
# theme = "onelight"
theme = "dracula"

[editor]
mouse = true
auto-format = true
auto-save = true
line-number = "relative"
bufferline = "always"
indent-guides.render = true
cursorline = true
color-modes = true
true-color = true
# auto-pairs = true
end-of-line-diagnostics = "hint"

# https://docs.helix-editor.com/master/editor.html?highlight=auto-pairs#editorauto-pairs-section
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'<' = '>'

[editor.inline-diagnostics]
cursor-line = "info"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
nbsp = 'all'
tab = 'all'
space = 'all'
[editor.whitespace.characters]
space = '·'
tab = '│'
tabpad = ' '

[keys.insert]
"A-h" = "move_char_left"
"A-j" = "move_line_down"
"A-k" = "move_line_up"
"A-l" = "move_char_right"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
"A-c" = ":clipboard-yank"
"A-v" = ":clipboard-paste-replace"
"A-w" = [":write", ":line-ending lf"]
"A-q" = ":buffer-close!"
"A-n" = ":new"
"A-h" = ":buffer-previous"
"A-l" = ":buffer-next"
"A-left" = ":buffer-previous"
"A-right" = ":buffer-next"
"A-r" = ":reload-all"
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
g = { a = "code_action" }
# "A-g" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
# C-f = [
#   ":new",
#   ":insert-output lf-pick",
#   ":theme default",
#   "select_all",
#   "split_selection_on_newline",
#   "goto_file",
#   "goto_last_modified_file",
#   ":buffer-close!",
#   ":theme onelight",
# ]

#"space" = { "t" = ":sh wezterm cli split-pane --bottom --percent 30 --cwd $(pwd)"}
