[tools]
lsd = "latest"
yazi = "latest"
lazygit = "latest"
zoxide = "latest"
lazydocker = "latest"
jq = "latest"
terraform = "latest"
rclone = "latest"
task = "latest"
uv = "latest"
python = "3.12.11"
go = "1.25.1"
yt-dlp = "latest"
zellij = "latest"
mc = "latest"
cloudflared = "latest"
typst = "latest"
marksman = "latest"
shfmt = "latest"
taplo = "latest"
terraform-ls = "latest"
shellcheck = "latest"
dust = "latest"
starship = "latest"
helix = "latest"
node = "24.11"
"npm:ansible-language-server" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:@perplexity-ai/mcp-server" = "latest"
"npm:eslint" = "latest"
chisel = "latest"
opencode = "latest"
# "npm:typescript-language-server" = "latest"
# "npm:typescript" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
